defaults:
  - _self_
  - report: null # for overriding
  - run_filter: proseco_vs_mlm # for overriding

name: ???
wandb_entity: ilm-extensions
wandb_project: BPTT

fields_of_interest:
  - seed
  - "loss.*"
  - "predictor.*"
  - "loss._target_"

summary_fields_of_interest:
  - val/prediction/exact_match
  - val/prediction/token_accuracy
  - test/prediction/exact_match
  - test/prediction/token_accuracy
  - val/total_perplexity_gpt2
  - val/nll_gpt2
  - val/length_gpt2
  - val/entropy_gpt2

rename_map:
  config.loss._target_: loss
  config.predictor.max_steps: sampling_steps
  config.predictor.confidence: confidence
  config.predictor.top_k: top_k
  config.predictor.top_p: top_p
  config.predictor.threshold: threshold
  config.seed: seed
  config.predictor.correction_frequency: correction_frequency
  config.predictor.correction_steps: correction_steps
  summary.val/prediction/exact_match: Exact Match (val)
  summary.val/prediction/token_accuracy: Token Accuracy (val)
  summary.test/prediction/exact_match: Exact Match (test)
  summary.test/prediction/token_accuracy: Token Accuracy (test)
  summary.val/total_perplexity_gpt2: Gen. Perplexity
  summary.val/nll_gpt2: Gen. NLL
  summary.val/length_gpt2: Gen. Length
  summary.val/entropy_gpt2: Gen. Entropy
  tags.model_type: Model
