# @package _global_
defaults:
  - default
  - /datasets@datamodule.dataset_managers.train.lm: gram_graph_coloring_train_10v
  - /datasets@datamodule.dataset_managers.val.lm: gram_graph_coloring_val_10v
  - /datasets@datamodule.dataset_managers.val.infill_prediction: gram_graph_coloring_val_10v
  - /collator@datamodule.dataset_managers.train.lm.collator: puzzle_mlm
  - /collator@datamodule.dataset_managers.val.lm.collator: puzzle_mlm
  - /collator@datamodule.dataset_managers.val.infill_prediction.collator: puzzle_infill_pred

datamodule:
  print_batch_fn: doublebackprop.datamodule.print_batch

tags:
  dataset: gram_graph_coloring_10v
